### ISSUE TITLE
mp-spdz docker build error

### ISSUE THREAD

**Issue by HuifengShrimp** [MPC-SoK/frameworks#64]
I can not build the docker image of mp-spdz, my steps are as follows:

- `git clone https://github.com/MPC-SoK/frameworks.git`
- `cd mp-spdz`
- `docker build -t mp-spdz .`

and the errors are as follows:
#9 331.4 Binaries are not available for aarch64

#9 331.4 Use the source distribution: https://github.com/data61/MP-SPDZ/#tldr-source-distribution
------
executor failed running [bash install.sh]: exit code: 1

**Comment by gutjuri** [comment]
This error stems from the installation script of MP-SPDZ: https://github.com/data61/MP-SPDZ/blob/master/Scripts/tldr.sh#L28

Are you using an ARM processor? In this case, we'd need to build our Docker image using MP-SPDZ's source distribution (see: https://github.com/data61/MP-SPDZ#tldr-source-distribution) by changing the [installation script](https://github.com/MPC-SoK/frameworks/blob/master/mp-spdz/install.sh). 

If you like you could try to tackle this problem and submit a PR. Otherwise, I'd take a look into it, but it may take a few weeks until I have access to an ARM machine and can test a potential fix.

**Comment by HuifengShrimp** [comment]
Yes, I am using the docker of Mac M1. When I clone the original MP-SPDZ program in the EzPC docker container, it works. I am not familiar with building the docker image, but I will try to figure it out.

**Comment by gutjuri** [comment]
I have provided a modified Dockerfile in #69, which should work on your processor.

Could you try to build the image using this Dockerfile (on branch `64-mpspdz-arm-build`)?

**Comment by gutjuri** [comment]
I have updated the repo's master branch as to allow building mp-spdz from source, which should solve your problem. Please see the updated readme (https://github.com/MPC-SoK/frameworks/blob/master/mp-spdz/README.md#docker-setup) for details. 

I'd be interested in your feedback. Please drop me a line if this update solved your problem.
