### ISSUE TITLE
-

### ISSUE THREAD

**Issue by dhejyuyr** [MPC-SoK/frameworks#85]

**Comment by gutjuri** [comment]
Hello,
am I right in assuming that you have found an answer to your question by yourself? In this case, I will close this issue. We are currently in the process of updating our examples, however, we did not yet update the Sharemind ones. When we do, we will include updated information on the license terms of Sharemind, since the current Sharemind README is five years old and probably outdated.

**Comment by dhejyuyr** [comment]
> Hello, am I right in assuming that you have found an answer to your question by yourself? In this case, I will close this issue. We are currently in the process of updating our examples, however, we did not yet update the Sharemind ones. When we do, we will include updated information on the license terms of Sharemind, since the current Sharemind README is five years old and probably outdated.

hello. yes, I have, sorry to distrub you.
